# Generated by Django 4.1.3 on 2022-11-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interface", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="conductivity",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=4
            ),
            preserve_default=False,
        ),
    ]
