# Generated by Django 4.1.3 on 2022-11-04 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("interface", "0002_record_conductivity"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="p_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="interface.patient",
            ),
            preserve_default=False,
        ),
    ]
