# Generated by Django 4.1.3 on 2022-11-04 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("interface", "0003_record_p_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="record",
            old_name="dialysate_temperature",
            new_name="dialyse_temperature",
        ),
        migrations.RenameField(
            model_name="record", old_name="heparin_volumn", new_name="heparin_volume",
        ),
    ]
