# Generated by Django 4.1.3 on 2022-11-07 08:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interface", "0004_alter_dialysis_after_weight_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dialysis",
            name="Ca",
            field=models.DecimalField(
                decimal_places=3, default=Decimal("0.0"), max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="dialysis",
            name="end_SBP",
            field=models.DecimalField(
                decimal_places=3, default=Decimal("0.0"), max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="dialysis",
            name="start_SBP",
            field=models.DecimalField(
                decimal_places=3, default=Decimal("0.0"), max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="dialysis",
            name="start_blood_speed",
            field=models.DecimalField(
                decimal_places=3, default=Decimal("0.0"), max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="dialysis",
            name="start_flow_speed",
            field=models.DecimalField(
                decimal_places=3, default=Decimal("0.0"), max_digits=5, null=True
            ),
        ),
    ]
