# Generated by Django 4.1.3 on 2022-11-09 06:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interface", "0005_alter_dialysis_ca_alter_dialysis_end_sbp_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dialysis",
            name="Ca",
            field=models.DecimalField(
                decimal_places=3, default=Decimal("0.0"), max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="dialysis",
            name="ESA",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="dialysis",
            name="after_weight",
            field=models.DecimalField(
                decimal_places=3, default=Decimal("0.0"), max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="dialysis",
            name="before_weight",
            field=models.DecimalField(
                decimal_places=3, default=Decimal("0.0"), max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="dialysis",
            name="channel",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="dialysis",
            name="conductivity",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.0"), max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="dialysis",
            name="end_SBP",
            field=models.DecimalField(
                decimal_places=3, default=Decimal("0.0"), max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="dialysis",
            name="estimate_dehydration",
            field=models.DecimalField(
                decimal_places=3, default=Decimal("0.0"), max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="dialysis",
            name="expect_dehydration",
            field=models.DecimalField(
                decimal_places=3, default=Decimal("0.0"), max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="dialysis",
            name="food",
            field=models.DecimalField(
                decimal_places=3, default=Decimal("0.0"), max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="dialysis",
            name="heparin",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="dialysis",
            name="ideal_weight",
            field=models.DecimalField(
                decimal_places=3, default=Decimal("0.0"), max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="dialysis",
            name="real_dehydration",
            field=models.DecimalField(
                decimal_places=3, default=Decimal("0.0"), max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="dialysis",
            name="set_dehydration",
            field=models.DecimalField(
                decimal_places=3, default=Decimal("0.0"), max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="dialysis",
            name="start_SBP",
            field=models.DecimalField(
                decimal_places=3, default=Decimal("0.0"), max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="dialysis",
            name="start_blood_speed",
            field=models.DecimalField(
                decimal_places=3, default=Decimal("0.0"), max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="dialysis",
            name="start_flow_speed",
            field=models.DecimalField(
                decimal_places=3, default=Decimal("0.0"), max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="dialysis",
            name="start_temperature",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.0"), max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="dialysis",
            name="temperature",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.0"), max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="dialysis",
            name="transfusion",
            field=models.DecimalField(
                decimal_places=3, default=Decimal("0.0"), max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="record",
            name="accumulation",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="record",
            name="dehydrate_speed",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="record",
            name="dialyse_temperature",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="record",
            name="heparin_volume",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
