# Generated by Django 4.1.3 on 2022-11-09 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interface", "0006_alter_dialysis_ca_alter_dialysis_esa_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="DP",
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name="record",
            name="SBP",
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name="record",
            name="TMP",
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name="record",
            name="accumulation",
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name="record",
            name="blood_speed",
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name="record",
            name="breath",
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name="record",
            name="dehydrate_speed",
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name="record",
            name="dialyse_temperature",
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name="record", name="flush", field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="record",
            name="heparin_volume",
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
