# Generated by Django 4.1.3 on 2022-11-09 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "interface",
            "0007_alter_record_dp_alter_record_sbp_alter_record_tmp_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="channel_confirmed",
            field=models.CharField(max_length=5),
        ),
    ]
