# Generated by Django 4.1.3 on 2022-11-09 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interface", "0008_alter_record_channel_confirmed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="SBP",
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name="record",
            name="breath",
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
