# Generated by Django 4.1.3 on 2022-12-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interface", "0010_record_prediction_alter_dialysis_end_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="feedback", name="is_noise",),
        migrations.RemoveField(model_name="feedback", name="r_id",),
        migrations.AddField(
            model_name="record", name="is_idh", field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="feedback", name="is_sign", field=models.BooleanField(),
        ),
    ]
