# Generated by Django 4.1.3 on 2022-12-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interface", "0012_feedback_d_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="is_idh",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
