# Generated by Django 4.2.6 on 2023-12-11 10:17

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0015_remove_warnings_pred_id_delete_predict_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Predict',
            fields=[
                ('pred_id', models.AutoField(primary_key=True, serialize=False)),
                ('pred_time', models.DateTimeField()),
                ('pred_idh', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=10, null=True)),
                ('d_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.dialysis')),
            ],
        ),
        migrations.CreateModel(
            name='Warnings',
            fields=[
                ('w_id', models.AutoField(primary_key=True, serialize=False)),
                ('dismiss_time', models.DateTimeField(auto_now_add=True)),
                ('empNo', models.IntegerField()),
                ('warning_SBP', models.DecimalField(decimal_places=3, max_digits=10)),
                ('warning_DBP', models.IntegerField()),
                ('pred_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.predict')),
            ],
        ),
    ]
