# Generated by Django 4.2.6 on 2023-12-11 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0016_predict_warnings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warnings',
            name='pred_id',
        ),
    ]
