# Generated by Django 4.2.6 on 2023-12-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0017_remove_warnings_pred_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predict',
            name='pred_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
