# Generated by Django 4.2.6 on 2023-12-26 05:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0019_predict_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='warnings',
            name='p_bed',
            field=models.CharField(default='--', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warnings',
            name='p_name',
            field=models.CharField(default='--', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='predict',
            name='pred_idh',
            field=models.DecimalField(decimal_places=10, default=Decimal('0.0'), max_digits=20, null=True),
        ),
    ]
