# Generated by Django 4.2.6 on 2024-01-10 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0021_alter_warnings_dismiss_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warnings',
            name='empNo',
            field=models.CharField(max_length=20),
        ),
    ]
