# Generated by Django 4.2.6 on 2024-01-10 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0022_alter_warnings_empno'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='idh_time',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
