# Generated by Django 4.2.7 on 2024-01-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0023_feedback_idh_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('n_id', models.AutoField(primary_key=True, serialize=False)),
                ('n_name', models.CharField(max_length=10)),
                ('empNo', models.CharField(max_length=20)),
            ],
        ),
    ]
