# Generated by Django 4.0.6 on 2024-01-23 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0024_nurse'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='empNo',
            field=models.CharField(default='--', max_length=20),
            preserve_default=False,
        ),
    ]
