# Generated by Django 4.2.6 on 2024-03-26 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0026_warnings_click_time_alter_warnings_dismiss_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialysis',
            name='random_code',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
