# Generated by Django 4.2.6 on 2024-06-18 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0028_feedback_drug_all_feedback_inject_all_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='drug_all',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='inject_all',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='is_drug',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='is_inject',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='is_nursing',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='is_other',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='is_setting',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='is_sign',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='nursing_all',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='other_all',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='setting_all',
        ),
        migrations.AddField(
            model_name='warnings',
            name='drug_all',
            field=models.CharField(default='--', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warnings',
            name='inject_all',
            field=models.CharField(default='--', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warnings',
            name='is_drug',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='warnings',
            name='is_inject',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='warnings',
            name='is_nursing',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='warnings',
            name='is_other',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='warnings',
            name='is_setting',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='warnings',
            name='is_sign',
            field=models.BooleanField(null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warnings',
            name='nursing_all',
            field=models.CharField(default='--', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warnings',
            name='other_all',
            field=models.CharField(default='--', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warnings',
            name='setting_all',
            field=models.CharField(default='--', max_length=100),
            preserve_default=False,
        ),
    ]
