# Generated by Django 5.1 on 2024-10-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0029_remove_feedback_drug_all_remove_feedback_inject_all_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warnings',
            name='handle_time',
            field=models.DateTimeField(null=True),
        ),
    ]
