# Generated by Django 5.1 on 2024-10-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0031_alter_warnings_handle_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warnings',
            name='handle_time',
            field=models.DateTimeField(null=True),
        ),
    ]
